name: real-time-radar
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - numpy==1.24.3
    - matplotlib==3.7.1
    - pyqt5==5.15.9
    - pyqt5-sip==12.12.2
    - pyqtgraph==0.13.3
    - pyserial==3.5
    - scipy==1.11.1
    - pyfftw==0.13.1
    - psutil==5.9.5
