name: real-time-radar
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - colorama==0.4.6
    - contourpy==1.1.1
    - cycler==0.12.1
    - fonttools==4.56.0
    - kiwisolver==1.4.5
    - matplotlib==3.7.5
    - numpy==2.2.2
    - opencv-python==4.11.0.86
    - packaging==24.2
    - pillow==11.1.0
    - pyparsing==3.2.1
    - python-dateutil==2.9.0.post0
    - six==1.17.0
    - tqdm==4.67.1
